### ISSUE TITLE
laravel 5.4 can't listen event "kernel.handled"

### ISSUE THREAD

**Issue by luyuqiang** [sarfraznawaz2005/querydumper#1]
```php
// Fired when laravel is done sending response. We use this event so that our
// response is not repeated
Event::listen('kernel.handled', function () {
    echo implode("", self::$queries);
});
```
When i use querydumper with laravel 5.4,i found i can't listen "kernel.handled".

**Comment by sarfraznawaz2005** [comment]
@luyuqiang Sorry I noticed that event is not supported by LV5.4. I don't have time to update this package any more. 

A far better solution is to use this package: https://github.com/barryvdh/laravel-debugbar

Thanks
